on: push
name: Test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Check Python version
        run: |
          python -V
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: poetry run pytest
      - run: poetry run black --check .
